version: '3.5'
services:
  api:
    build: .
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    ports:
      - 5000:5000
    networks:
      - backend
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - backend
    pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
      networks:
        - my_backend_network

volumes:
  pg_data: null
networks:
  backend:
    name: my_backend_network
