version: "3.8"
services:
  app:
    image: schumixer/api_ip
    deploy:
      replicas: 2
  nginx:
    image: schumixer/nginx
    ports: 
      - 83:83
    depends_on:
      - app
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager