version: '3.8'
services:
  db:
    image: mongo
    restart: always
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
    networks:
      - fastapi
networks:
  fastapi:
    name: fastapi
volumes:
  data: