version: '3.8'
services:
  api:
    build: api
    restart: always
    environment:
      - .env
    ports:
      - 5000:5000
    networks:
      - backend
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - backend
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - backend

volumes:
  pg_data: 
networks:
  backend:
    name: backend
