version: '3.8'
services:
  rabbit:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_PASS: "1234"
      RABBITMQ_DEFAULT_USER: "user"